package io.altar.jeeexample.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Abstract base class for all entities in the application. This class provides
 * common functionality and attributes that all entities share. It uses JPA
 * annotations to define the entity structure and mapping.
 */
@MappedSuperclass
public abstract class Entity_ {

	/**
	 * The unique identifier of the entity.
	 */
	@Id
	/**
	 * The ID is automatically generated by the database.
	 */
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	/**
	 * Gets the unique identifier of the entity.
	 * 
	 * @return The ID of the entity
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the unique identifier of the entity.
	 * 
	 * @param id The ID to set
	 */
	public void setId(long id) {
		this.id = id;
	}

}
